import{a as j}from"./assets/vendor-bdb8a163.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function c(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=c(e);fetch(e.href,o)}})();document.getElementById("toggle-night-mode").addEventListener("click",function(){document.body.classList.toggle("night-mode")});document.addEventListener("DOMContentLoaded",function(){const t=[{title:"Wallet webservice",image:"/img/5-my-projects/image1.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"},{title:"Green harvest webservice",image:"/img/5-my-projects/image2.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"},{title:"English Exellence website",image:"/img/5-my-projects/image3.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"},{title:"mimino website",image:"/img/5-my-projects/image4.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"},{title:"power pulse webservice ",image:"/img/5-my-projects/image5.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"},{title:"chego jewelry website",image:"/img/5-my-projects/image6.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"},{title:"energy flow webservice",image:"/img/5-my-projects/image7.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"},{title:"fruitbox online store",image:"/img/5-my-projects/image8.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"},{title:"vyshyvanka vibes Landing Page",image:"/img/5-my-projects/image9.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"},{title:"starlight studio landing page",image:"/img/5-my-projects/image10.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"}];let n=0;const c=3,l=document.getElementById("project-list"),e=document.getElementById("load-more");function o(){for(let i=0;i<c;i++){if(n>=t.length){e.style.display="none";break}const s=t[n],m=document.createElement("li");m.innerHTML=`
                <img class="project-image" src="${s.image}" alt="${s.title}">
                <div class="project-info">
                <p class="project-technologies">${s.technologies}</p>
                    <p class="project-title">${s.title}</p>
                    <button class="project-link" onclick="window.open('${s.link}', '_blank')">VISIT</button>
                </div>
            `,l.appendChild(m),n++}}e.addEventListener("click",o),o()});const w=document.body,f=document.querySelector(".together-form"),u=document.getElementById("together-modal"),L=document.querySelector(".together-modal-close"),d=document.querySelector(".together-error"),b=document.querySelector(".together-ok"),k=`
    <div id="together-modal" class="together-modal";">
        <div class="together-modal-content">
            <button class="together-modal-close">
                <svg class="together-modal-svg" width="24" height="24">
                    <use href="./img/icons.svg#icon-x"></use>
                </svg>
            </button>
            <h3 class="together-modal-title">Thank you for your interest in cooperation!</h3>
            <p class="together-modal-text">The manager will contact you shortly to discuss further details and opportunities for cooperation. Please stay in touch.</p>
        </div>
    </div>
`;w.insertAdjacentHTML("beforeend",k);f.addEventListener("submit",async t=>{t.preventDefault();const n=new FormData(f);try{(await j.post("https://portfolio-js.b.goit.study/api/requests",n)).status===200?(d.style.display="none",u.style.display="flex",b.style.display="block",f.reset()):d.style.display="block"}catch{d.style.display="block"}});L.addEventListener("click",()=>{u.style.display="none"});window.addEventListener("click",t=>{t.target===u&&(u.style.display="none")});d?d.style.display="none":console.error("Error element not found in the DOM");document.addEventListener("DOMContentLoaded",function(){const t=document.querySelector("#footer");function n(){const c=t.getBoundingClientRect().top,l=window.innerHeight;c<l&&t.classList.add("visible")}window.addEventListener("scroll",n),n()});(()=>{const t={openModalBtn:document.querySelector("[data-menu-open]"),closeModalBtn:document.querySelector("[data-menu-close]"),modal:document.querySelector("[data-menu]")};t.openModalBtn.addEventListener("click",n),t.closeModalBtn.addEventListener("click",n);function n(){t.modal.classList.toggle("is-open")}function c(){function l(o,i){let s=document.querySelector(o);if(!s){console.log("елемент куди скролити не знайдено:",o);return}let m=s.getBoundingClientRect().top,h=window.pageYOffset,p=null;const v=function(r,a,g,S){return r/=S/2,r<1?g/2*r*r+a:(r--,-g/+a)},y=function(r){p===null&&(p=r);const a=r-p,g=v(a,h,m,i);window.scrollTo(0,g),a<i&&requestAnimationFrame(y)};requestAnimationFrame(y)}const e=document.querySelectorAll("a.scroll-to");e&&e.forEach(o=>{o.addEventListener("click",function(i){i.preventDefault();const s=this.getAttribute("href");t.modal.classList.contains("is-open")&&t.modal.classList.remove("is-open"),l(s,1e3)})})}c()})();document.addEventListener("DOMContentLoaded",function(){const t=document.querySelector(".scroll-to-top");window.addEventListener("scroll",()=>{window.scrollY>300?t.style.display="block":t.style.display="none"}),t.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})})});
//# sourceMappingURL=commonHelpers.js.map
