(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();document.getElementById("toggle-night-mode").addEventListener("click",function(){document.body.classList.toggle("night-mode")});document.addEventListener("DOMContentLoaded",function(){const o=[{title:"Wallet webservice",image:"/img/5-my-projects/image1.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"},{title:"Green harvest webservice",image:"/img/5-my-projects/image2.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"},{title:"English Exellence website",image:"/img/5-my-projects/image3.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"},{title:"mimino website",image:"/img/5-my-projects/image4.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"},{title:"power pulse webservice ",image:"/img/5-my-projects/image5.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"},{title:"chego jewelry website",image:"/img/5-my-projects/image6.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"},{title:"energy flow webservice",image:"/img/5-my-projects/image7.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"},{title:"fruitbox online store",image:"/img/5-my-projects/image8.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"},{title:"vyshyvanka vibes Landing Page",image:"/img/5-my-projects/image9.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"},{title:"starlight studio landing page",image:"/img/5-my-projects/image10.jpg",technologies:"React, JavaScript, Node JS, Git",link:"#"}];let i=0;const r=3,l=document.getElementById("project-list"),e=document.getElementById("load-more");function t(){for(let n=0;n<r;n++){if(i>=o.length){e.style.display="none";break}const c=o[i],d=document.createElement("li");d.innerHTML=`
                <img class="project-image" src="${c.image}" alt="${c.title}">
                <div class="project-info">
                <p class="project-technologies">${c.technologies}</p>
                    <p class="project-title">${c.title}</p>
                    <button class="project-link" onclick="window.open('${c.link}', '_blank')">VISIT</button>
                </div>
            `,l.appendChild(d),i++}}e.addEventListener("click",t),t()});document.addEventListener("DOMContentLoaded",function(){const o=document.querySelector("#footer");function i(){const r=o.getBoundingClientRect().top,l=window.innerHeight;r<l&&o.classList.add("visible")}window.addEventListener("scroll",i),i()});(()=>{const o={openModalBtn:document.querySelector("[data-menu-open]"),closeModalBtn:document.querySelector("[data-menu-close]"),modal:document.querySelector("[data-menu]")};o.openModalBtn.addEventListener("click",i),o.closeModalBtn.addEventListener("click",i);function i(){o.modal.classList.toggle("is-open")}function r(){function l(t,n){let c=document.querySelector(t);if(!c){console.log("елемент куди скролити не знайдено:",t);return}let d=c.getBoundingClientRect().top,u=window.pageYOffset,m=null;const f=function(s,a,g,y){return s/=y/2,s<1?g/2*s*s+a:(s--,-g/+a)},p=function(s){m===null&&(m=s);const a=s-m,g=f(a,u,d,n);window.scrollTo(0,g),a<n&&requestAnimationFrame(p)};requestAnimationFrame(p)}const e=document.querySelectorAll("a.scroll-to");e&&e.forEach(t=>{t.addEventListener("click",function(n){n.preventDefault();const c=this.getAttribute("href");o.modal.classList.contains("is-open")&&o.modal.classList.remove("is-open"),l(c,1e3)})})}r()})();document.addEventListener("DOMContentLoaded",function(){const o=document.querySelector(".scroll-to-top");window.addEventListener("scroll",()=>{window.scrollY>300?o.style.display="block":o.style.display="none"}),o.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})})});
//# sourceMappingURL=commonHelpers.js.map
